export const EVENT_OBSERVED_COLUMNS = [
  'calendar_id',
  'href',
  'summary',
  'description',
  'location',
  'start',
  'end',
  'all_day',
  'color',
  'attendees',
  'organizer_email',
  'talk_url',
  'is_recurring',
  'rrule',
  'alarm_minutes',
  'alarms',
  'is_task',
];

export const CALENDAR_OBSERVED_COLUMNS = [
  'display_name',
  'color',
  'ctag',
  'url',
  'slug',
  'is_subscribed',
  'is_read_only',
  'source_url',
  'supports_events',
];
