name: Plumber

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  plumber:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: getplumber/plumber@7ad9d267ee5a00163cec9e5c749a088d5f565167 # v0.4.26
        with:
          score-push: true
